# Generated by Django 4.2.5 on 2024-01-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donername', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('bloodgroup', models.CharField(choices=[('ab', 'AB'), ('a', 'A+'), ('b', 'B+'), ('o', 'O+')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='departments',
            field=models.CharField(choices=[('gynocology', 'GYNOCOLOGY'), ('ent', 'ENT'), ('cardiology', 'CARDIOLOGY'), ('neurology', 'NEUROLOGY'), ('orthopedic', 'ORTHOPEDIC')], max_length=20),
        ),
    ]
